### ISSUE TITLE
Automated tests for extensions

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/extension_tester#3]
We've been thinking a bit about tests that could be useful, including:

* [ ] Does the extension provide an ```id``` property for each object it introduces (required vs. recommended?)
* [ ] Does the example data provided in the extension repo validate against the extension
* [ ] Does a schema with the extension provided still validate our sample data (we might need to create better sample data for this)

**Comment by Bjwebb** [comment]
As a first step towards this, I've set up the current extension_tests tests to run against every extension in the registry. https://github.com/open-contracting/extension_tester/blob/master/test_registry.py

This is run every night using Travis cron https://travis-ci.org/open-contracting/extension_tester/builds

**Comment by jpmckinney** [comment]
1. I created https://github.com/open-contracting/standard-development-handbook/issues/75 about authoring guidance instead of writing a strict test for the presence of `id`.
2. I created https://github.com/open-contracting/ocds-extensions/issues/34 about how extensions publish example data.
3. I think this is done by `test_fakedata`.
